pipeline:
  publish-container-image:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      # Replace this with your own Git host
      repo: git.mattcen.com/${DRONE_REPO}
      context: django/
      dockerfile: django/Dockerfile
      platforms: linux/amd64,linux/arm64/v8
      # Replace this with your own Git host
      cache_from: git.mattcen.com/${DRONE_REPO}
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: push
