version: "3.8"

services:
  db:
    image: postgis/postgis
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    image: mattcen/radioactiv8
    command: gunicorn geodjango.wsgi -b 0.0.0.0:8000
    env_file: .env
    volumes:
      - static_files:/static
    depends_on:
      db:
        condition: service_healthy

  web:
    build: ./nginx
    image: mattcen/nginx_django
    ports:
      - "$APP_PORT:80"
    depends_on:
      - app
    volumes:
      - static_files:/static


volumes:
  db_data: {}
  static_files:
