version: "3.8"

services:
  db:
    image: postgis/postgis
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: ./RadioActiv8
    image: mattcen/radioactiv8
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    volumes:
      - ./RadioActiv8:/code
    ports:
      - "$APP_PORT:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: {}
